name: ci

on:
  pull_request:
    branches:
      - 'release/**'
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: '--ios --runtime-mode=release'
            prefix: ios_release
          - mode: '--ios --runtime-mode=debug'
            prefix: ios_debug
          - mode: '--unoptimized --mac-cpu arm64'
            prefix: host_debug_unopt_arm64

    steps:

      - name: Setup depot_tools
        shell: bash
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "${{ github.workspace}}/depot_tools"  >> $GITHUB_PATH

      - name: Setup environment
        shell: bash
        run: |
          #cp engine/scripts/standard.gclient .gclient
          #gclient sync
          cat > .gclient <<- EOF
          solutions = [
            {
              "managed": False,
              "name": ".",
              "url": "https://github.com/abaltatech/flutter.git",
              "custom_deps": {},
              "deps_file": "DEPS",
              "safesync_url": "",
            },
          ]
          EOF

          gclient sync -j4 -v

      - name: Fetch source
        shell: bash
        run: |
          git fetch origin ${{ github.ref }}
          git checkout FETCH_HEAD

      - name: Re-fetch dependencies
        shell: bash
        run: |
          gclient sync -j4 -v

      - name: Generate build files
        shell: bash
        working-directory: engine/src
        run: |
          ./flutter/tools/gn ${{ matrix.mode }}

      - name: Build
        shell: bash
        working-directory: engine/src
        run: |
          flutter/third_party/ninja/ninja -C out/${{ matrix.prefix }}/

          if [[ "${{ matrix.prefix }}" == "ios_release" ]]; then
            mkdir -p out/ios_release_to_upload
            cp -R out/${{ matrix.prefix }}/Flutter.xcframework out/ios_release_to_upload
            cd out/ios_release_to_upload
            zip -r ../${{ matrix.prefix }}.zip Flutter.xcframework
          else
            cd out
            zip -r ${{ matrix.prefix }}.zip ${{ matrix.prefix }}
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.prefix != 'ios_release' }}
        with:
          name: ${{ matrix.prefix }}
          path: |
            engine/src/out/${{ matrix.prefix }}

      - uses: actions/upload-artifact@v4
        if: ${{ matrix.prefix == 'ios_release' }}
        with:
          name: ${{ matrix.prefix }}
          path: |
            engine/src/out/ios_release_to_upload

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            engine/src/out/${{ matrix.prefix }}.zip



