name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version (format: x.y.z)"
        required: true
      ref:
        description: "Git reference (branch or commit SHA)"
        required: true

jobs:
  create-tag:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:

      - name: Validate Version Format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?(\+([0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*))?$ ]]; then
            echo "Error: Version format must semantic version compatible https://semver.org/"
            exit 1
          fi

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 1159088
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ inputs.ref }}

      - name: Configure credentials
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}
